---
abstract: "Like Exporter, but add a '-base' flag to declare a class as a child"
author:
  - 'Olivier Mengue <dolmen@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  t::lib::Child1: 0
  t::lib::Mother: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300010, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exporter-WithBase
requires:
  Exporter: 5.57
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/dolmen/p5-Exporter-WithBase
  repository: https://github.com/dolmen/p5-Exporter-WithBase.git
version: 0.01
