---
abstract: "Like Exporter, but add a '-base' flag to declare a class as a child"
author:
  - 'Olivier Mengue <dolmen@cpan.org>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Exporter-WithBase
requires:
  Exporter: '5.57'
  perl: '5.006'
  strict: '0'
  warnings: '0'
version: '0.02'
